# Generated by Django 6.1.1 on 2026-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Exercício')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo Muscular')),
                ('repeticoes', models.IntegerField(verbose_name='Repetições')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluido')),
            ],
            options={
                'verbose_name': 'Exercicio',
                'verbose_name_plural': 'Exercicios',
            },
        ),
    ]
